image: nvidia/cuda:11.3.0-devel-ubuntu20.04

stages:
  - build and test
  - doc
  - publish

.reports: &ready_reports
  - mkdir -p build/reports/

build-test-debug:
  stage: build and test
  tags: [k8srunner-gpu]
  before_script:
    - *ready_reports
    # We need CMake >= 3.21.0 for the --output-junit option on CTest.
    - DEBIAN_FRONTEND=noninteractive apt-get -y update
    - DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential gpg wget
    - wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
    - echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ focal main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null
    - DEBIAN_FRONTEND=noninteractive apt-get -y update
    - rm /usr/share/keyrings/kitware-archive-keyring.gpg
    - DEBIAN_FRONTEND=noninteractive apt-get -y install kitware-archive-keyring
    - DEBIAN_FRONTEND=noninteractive apt-get -y install cmake
    - DEBIAN_FRONTEND=noninteractive apt-get -y install lcov python3
    - export LD_LIBRARY_PATH=/usr/local/cuda/lib:/usr/local/cuda/lib64:$LD_LIBRARY_PATH
    - nvidia-smi
    - mkdir debug
    - cd debug/
    - cmake ../ -DCOVERAGE_REPORT=ON -DCUDA_ARCH=6.1
  script:
    - make -j
    - make coverage
  after_script:
    - mv debug/coverage.xml build/reports/code-coverage.xml
    - mv debug/coverage/ ./
  artifacts:
    paths:
      - build/
      - coverage/
    reports:
      cobertura: build/reports/code-coverage.xml

build-test-release:
  stage: build and test
  tags: [k8srunner-gpu]
  variables:
    LS_CMD: 'ls -l release'
  before_script:
    - *ready_reports
    # We need CMake >= 3.21.0 for the --output-junit option on CTest.
    - DEBIAN_FRONTEND=noninteractive apt-get -y update
    - DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential gpg wget
    - wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
    - echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ focal main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null
    - DEBIAN_FRONTEND=noninteractive apt-get -y update
    - rm /usr/share/keyrings/kitware-archive-keyring.gpg
    - apt-get -y install kitware-archive-keyring
    - apt-get -y install cmake
    - export LD_LIBRARY_PATH=/usr/local/cuda/lib:/usr/local/cuda/lib64:$LD_LIBRARY_PATH
    - cmake --version
    - nvidia-smi
    - mkdir release
    - cd release/
    - cmake ../ -DCUDA_ARCH=6.1
  script:
    - make -j
    - ctest --output-junit unit-tests.xml
  after_script:    
    - mv release/unit-tests.xml build/reports/
  artifacts:
    paths:
      - build/
    reports:
      junit: build/reports/unit-tests.xml

linting:
  stage: build and test
  before_script:
    - *ready_reports
    - DEBIAN_FRONTEND=noninteractive apt-get -y update
    - DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential clang-tidy gpg wget
    - wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
    - echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ focal main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null
    - DEBIAN_FRONTEND=noninteractive apt-get -y update
    - rm /usr/share/keyrings/kitware-archive-keyring.gpg
    - apt-get -y install kitware-archive-keyring
    - apt-get -y install cmake
    - mkdir release
    - cd release/
    - cmake ../ -DCUDA_ARCH=6.1 -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
  script:
    - echo "Running lint check"
    - run-clang-tidy -quiet '^(?:(?!extern/|test/).)*$\r?\n?' > clang-tidy.out
    - cat clang-tidy.out | ../scripts/clang-tidy-to-junit/clang-tidy-to-junit.py ../ > linting.xml
  after_script:
    - echo $(pwd)
    - mv release/linting.xml build/reports/
  artifacts:
    paths:
      - build/

build-docs:
  stage: doc
  variables:
    LS_CMD: 'ls -l *'
  before_script:
    - DEBIAN_FRONTEND=noninteractive apt-get -y update
    - DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential cmake 
    - DEBIAN_FRONTEND=noninteractive apt-get -y install python3 python3-sphinx python3-pip doxygen
    - pip3 install breathe
    - pip3 install sphinx-rtd-theme
    - mkdir build-docs
  script:
    - make doc_html
  after_script:
    - echo $(pwd)
    - 'eval "$LS_CMD"'
    - mv docs/build/html/ build-docs/
  artifacts:
    paths:
      - build-docs/docs/build/html/
    expire_in: 3600 seconds


pages:
  stage: publish
  image: alpine
  dependencies:
    - build-docs
    - build-test-debug
  script:
    - rm -rf public
    - mkdir -p public
    - mv coverage/ public/
    - mv build-docs/docs/build/html/* public/
  artifacts:
    paths:
      - public
#    expire_in: never

# Create Gitlab CI badges from CI metrics
# https://developer.skao.int/en/latest/tools/continuousintegration.html#automated-collection-of-ci-health-metrics-as-part-of-the-ci-pipeline
include:
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/post_step.yml'
